version: '3'
networks:     
    homeland:
      driver: bridge    
services:   
  config-server:
    image: johnjonathan/spring-cloud-config-server:1.0.0
    container_name: config-server
    ports: 
      - 8888:8888
    volumes:
      - ./config:/config
    environment: 
      - SPRING_PROFILES_ACTIVE=native
      - BANNER_LOCATION=file:/config/banner.txt
    networks: 
      - homeland