info:
  component: Config Server
spring:
  application:
    name: config-server
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo          
management:
  context_path: /admin
encrypt:
  enabled: false