info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: /config
        bootstrap: true
encrypt:
  enabled: false