#mongodb
spring:
  data:
    mongodb:      
      password: '{cipher}1e1dfeef5567c47c4697975f8b79666e39a2adffbe6d606e07203b9d8191f06c'
      uri: mongodb://waes_user:${spring.data.mongodb.password}@localhost:27017/waes_api?retryWrites=true&w=majority